name: bao
description: Dart bindings for Bao. Bao is a library for encrypted data storage and exchange. 
version: 0.0.3
repository: https://github.com/stregato/bao

data:
  - assets/**

environment:
  sdk: ^3.5.0
  flutter: ">=2.0.0"

# Add regular dependencies here.
dependencies:
  archive: ^3.3.5
  crypto: ^3.0.2
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  http: ^0.13.6
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  bootstrap: bootstrap
